### ISSUE TITLE
Request for Solstice munki recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/MLBZ521-recipes#12]
Any chance that you might add a solstice.munki recipe to your repo, as https://github.com/autopkg/chalcahuite-recipes/blob/master/Solstice/Solstice.munki.recipe is being deprecated? Many thanks.

**Comment by dcoobs** [comment]
I've created the following recipe which utilizes the download/pkg recipes from this repo:
https://github.com/autopkg/dcoobs-recipes/blob/master/Solstice/Solstice.munki.recipe

I'm more than happy to make a pull request to merge it into this repo if desired.

**Comment by MLBZ521** [comment]
Sorry for the delay...been really busy recently.

@eshirk Unfortunately, I haven't used Munki in....five plus years (~2015), so I wouldn't say I'd be the best to create and maintain said recipe.

@dcoobs You _can_, but as I mentioned above, I wouldn't be the best to maintain it.  Leaving it in your repo seems perfectly fine to me.

Happy to take other opinions though.

**Comment by flammable** [comment]
I'm using these recipes, and they work great:

https://github.com/autopkg/joshua-d-miller-recipes/tree/master/Mersive

**Comment by eshirk** [comment]
Awesome--thanks!
