### ISSUE TITLE
Problem with maple Patch.jss.recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/MLBZ521-recipes#15]
Seeing this with our Autopkg run this morning:

 WARNING: plist error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/Maple/Maple Patch.jss.recipe: unexpected key at line 36

**Comment by eshirk** [comment]
Looks like there's already a pull request for this issue....

**Comment by MLBZ521** [comment]
Should be resolved in PR #14.

Sorry about that.  Must have been a failed copy/paste last night. 😅
