### ISSUE TITLE
URL in ARCHICADUpdatesProcessor.py yields 404

### ISSUE THREAD

**Issue by jutonium** [autopkg/MLBZ521-recipes#16]
The new URL seems to be:
https://graphisoft.com/ww/service/downloads/archicad-updates

**Comment by MLBZ521** [comment]
@jutonium Sorry for the delay on this.  Just applied the updates (47f8af6) you shared from your repo.  Thanks for that.  Feel free to send a PR in the future if you'd like!

Thanks again!
