### ISSUE TITLE
Info.plist' does not exist or could not be read.

### ISSUE THREAD

**Issue by macchrister** [autopkg/MLBZ521-recipes#17]
Error in local.jss.Zoom-ForIT: Processor: Versioner: Error: File '/Users/administrator/Library/AutoPkg/Cache/local.jss.Zoom-ForIT/payload/Contents/Info.plist' does not exist or could not be read.

pkg structure def changed with 5.3.
it's now a distribution pkg
the Payload is in the component pkg inside the distribution pkg

**Comment by MLBZ521** [comment]
Thanks @macchrister for the heads up.  This should be resolved.
