### ISSUE TITLE
Crowdstrike API URL Changes

### ISSUE THREAD

**Issue by wburnett** [autopkg/MLBZ521-recipes#20]
Hi Zach,

I was setting up a new instance of Crowdstrike and noticed there is now more than one base URL in use.

In addition to https://api.crowdstrike.com/..." there is now also "https://api.us-2.crowdstrike.com/...", would it be possible to add this as an input to the download recipe?

**Comment by wburnett** [comment]
Opened a PR with a functional solve: https://github.com/autopkg/MLBZ521-recipes/pull/22

**Comment by MLBZ521** [comment]
#22 has been merged with 8bd29e9.

I greatly apologize for the delay getting this merged.

Thanks for the PR!.
