### ISSUE TITLE
Solstice app not in the expected location

### ISSUE THREAD

**Issue by Chalcahuite** [autopkg/MLBZ521-recipes#23]
Not sure when it happened, but Mersive change the app name from Solstice Client to Mersive Solstice and that results in the following error in the recipe

> The Solstice Client.app wasn't at the expected location.
> Failed.
> Receipt written to /Users/user/Library/AutoPkg/Cache/local.jss.Solstice/receipts/Solstice-receipt-20210105-171902.plist

Fix is relatively simple, just need to change Solstice Client to Mersive Solstice in the Solstice Processor. I'll make a PR.

**Comment by MLBZ521** [comment]
Thanks @Chalcahuite.  This may be why I saw an error recently.  But when I ran it again, it seemed to complete without an error, which was confusing.  But I didn't have the time to look into it much at that point.

I have Merged your PR.
