### ISSUE TITLE
XeroxPrintDriverProcessor no longer outputs valid URL

### ISSUE THREAD

**Issue by jazzace** [autopkg/MLBZ521-recipes#27]
It appears that Xerox has changed things again on their web site. The XeroxPrintDriverProcessor no longer needs to preface the URL it fetches with https://www.support.xerox.com. For example, when trying to retrieve the drivers for the Phaser 7500, the output of the processor is now `https://www.support.xerox.comhttps://download.support.xerox.com/pub/drivers/ALB80XX/drivers/macOS10_13/pt_BR/XeroxDrivers_5.7.2_2221.dmg`.

**Comment by MLBZ521** [comment]
@jazzace I'll try to get to this this week.  Thanks for the FYI.  👍
