### ISSUE TITLE
"Google Drive File Stream" is now just "Google Drive"

### ISSUE THREAD

**Issue by skoobasteeve** [autopkg/MLBZ521-recipes#29]
Seems like Google is re-branding File Stream to "Google Drive" and thus changed the package and app names. As expected, this causes the pkg recipe to fail in more than one location:

`Processor: FlatPkgUnpacker: Error: No valid path found as given by 'flat_pkg_path': /Users/raymondlyon/Library/AutoPkg/Cache/local.jss.GoogleDriveFileStream-riskified/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg
`

`Processor: PkgPayloadUnpacker: Error: extraction of /Users/raymondlyon/Library/AutoPkg/Cache/local.jss.GoogleDriveFileStream-riskified/expanded/GoogleDriveFileStream.pkg/Payload with ditto failed: ditto: /Users/raymondlyon/Library/AutoPkg/Cache/local.jss.GoogleDriveFileStream-riskified/expanded/GoogleDriveFileStream.pkg/Payload: No such file or directory`

 Opened Pull Request #28 which fixes this issue in the pkg recipe by updating the file names to match the new package.

**Comment by MLBZ521** [comment]
Merged #28.

Thanks!
