### ISSUE TITLE
Error updating repo

### ISSUE THREAD

**Issue by ehlersmj4814** [autopkg/MLBZ521-recipes#33]
I am getting an error when attempting to update the recipes repo.

ERROR: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'alpha@autopkg.(none)')

**Comment by homebysix** [comment]
Hi @ehlersmj4814 - Are you able to update other repos?

You might try `autopkg repo-delete MLBZ521-recipes && autopkg repo-add MLBZ521-recipes` as an alternative.

**Comment by MLBZ521** [comment]
Yes, please try what Elliot suggested above.

**Comment by jazzace** [comment]
FWIW, the error I received was:
```
WARNING: plist error for /Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/Android Studio/AndroidStudioSDKCLITools.pkg.recipe: not well-formed (invalid token): line 94, column 1
```
Deleting and re-adding the repo solved the problem. I haven't ruled out that this was a problem with the new release of AutoPkgr (which was responsible for the repo update and threw an error upon update but continued to function with the above caveat).

**Comment by MLBZ521** [comment]
Closing this issue at this time, removing and re-adding should resolve this, as mentioned.  Sorry for the hassle all.
