### ISSUE TITLE
GoogleDriveFileStream.pkg.recipe can't pull version from package

### ISSUE THREAD

**Issue by skoobasteeve** [autopkg/MLBZ521-recipes#35]
Getting the below error:

extraction of /Users/riskiadmin/Library/AutoPkg/Cache/local.jss.GoogleDriveFileStream-riskified/expanded/GoogleDrive.pkg/Payload with ditto failed: ditto: /Users/riskiadmin/Library/AutoPkg/Cache/local.jss.GoogleDriveFileStream-riskified/expanded/GoogleDrive.pkg/Payload: No such file or directory

This is due to Google adding multiple sub-packages for arm and x86. Fixed with Pull Request #34

**Comment by MLBZ521** [comment]
Forgot to close this I guess.  #34 was merged a while back.
