### ISSUE TITLE
MySQLCommunityServer.pkg.recipe does not set pkg_path

### ISSUE THREAD

**Issue by grahampugh** [autopkg/MLBZ521-recipes#40]
`MySQLCommunityServer.pkg.recipe` is not setting `pkg_path` because you are using the `Copier` processor instead of the `PkgCopier` processor. My suggestion is that you switch to the `PkgCopier` processor so that subsequent `.jss` or `.jamf` recipes pick up the package.

**Comment by MLBZ521** [comment]
Thanks for the suggestion Graham.  I've made the recommended changes in the above commits.

**Comment by grahampugh** [comment]
Thanks!
