### ISSUE TITLE
Error in Pharos Popup Client recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/MLBZ521-recipes#41]
Seeing the following:

WARNING: yaml error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/Pharos Popup Client/Pharos Popup Client.jss.recipe.yaml: while scanning for the next token
found character '\t' that cannot start any token

**Comment by joeschlimmer-ic** [comment]
I am seeing this as well.

**Comment by MLBZ521** [comment]
This should be resolved at this time.  Sorry for the failure to review.
