### ISSUE TITLE
Zoom-OutlookPlugin.pkg recipe does not populate pkg_path variable

### ISSUE THREAD

**Issue by Darks7ar** [autopkg/MLBZ521-recipes#44]
When run, the final active phase using the Copier processor does not export the pkg_path variable, which every pkg recipe should export. Recommend converting that process over to the PkgCopier processor, which exports this variable.

**Comment by Darks7ar** [comment]
Pull request #45 made to remediate this issue.

**Comment by MLBZ521** [comment]
I've merged this finally.  Sorry for the delay.
