### ISSUE TITLE
OfflineApps.py - issue when not using sub-folder to store content

### ISSUE THREAD

**Issue by DrWebster** [autopkg/MLBZ521-recipes#48]
I'm trying to use the Mathematica pkg recipe in AutoPkgr and am running across a problem that's got me stumped. I created an override for the recipe so I could customize it, then updated the "FILE_SHARE" key to an appropriate local path where I'm dropping the .dmg. When I run it, though, I get the following error:

`WARNING: plist error for /Users/drwebster/Library/AutoPkg/RecipeRepos/com.github.UWO-MIO.UWO-AutoPkg/MicrosoftSilverlight/Silverlight.install.recipe: junk after document element: line 35, column 0
WARNING: plist error for /Users/drwebster/Library/AutoPkg/RecipeRepos/com.github.UWO-MIO.UWO-AutoPkg/Packages/Packages.munki.recipe: junk after document element: line 189, column 0
Failed local trust verification.`

It's the only recipe I'm running, yet the error references recipes from another repo? Any ideas?

**Comment by homebysix** [comment]
[PR submitted](https://github.com/UWO-MIO/UWO-AutoPkg/pull/2) for the syntax issues upstream.

**Comment by DrWebster** [comment]
> AutoPkg scans all recipes in your recipe search path in order to determine parent relationships and look up custom processors, so it's expected that syntax errors in other repos might appear.
> 
> If you don't need those repos (e.g. for their parent recipes) you can use `repo-delete` to remove them. If you do need them, you might consider submitting a PR to their GitHub with the needed syntax fixes.

Thanks! I disabled that repo and I'm getting further along, but still running across an error:

`/Users/drwebster/Library/AutoPkg/Cache/local.pkg-custom.Mathematica/downloads/Mathematica_13.1.0_MAC.dmg is not mounted
Failed.`

It's finding the .dmg I placed in the "file share" (just a folder I created in ~/Documents/autopkg-temp) and copying it to the above downloads directory, so it seems to be failing when trying to mount it?

**Comment by MLBZ521** [comment]
@DrWebster Sorry for the delay, I've been on vacation for a weeks and catching up on things.

Can you provide a verbose (at least `-vv`, but more would likely help) run of your `autopkg run` so I can see what it's actually failing on?  You can redact any information that you don't want to share.

**Comment by DrWebster** [comment]
@MLBZ521 so I normally use AutoPkgr (the GUI). I created an override for the Mathematica.download recipe so I could customize the FILE_SHARE key. When I run the override from the CLI, here's the output:

`drw-mac:~ drwebster$ autopkg run Mathematica.download.local -vv
Processing Mathematica.download.local...
com.github.mlbz521.SharedProcessors/OfflineApps
{'Input': {'exception_string': 'Patch',
           'limitation_string': '',
           'major_version': '',
           'max_depth': '1',
           'search_path': '/Users/drwebster/Documents/autopkg/',
           'search_string': 'Mathematica',
           'version_separator': '-'}}
OfflineApps: No value supplied for OFFLINEAPPS_SMB_PORT, setting default value of: 445
OfflineApps: No value supplied for OFFLINEAPPS_SMB_MOUNT_POINT, setting default value of: /private/tmp/OfflineApps
OfflineApps: No value supplied for check_filesize, setting default value of: True
OfflineApps: Matched:  Mathematica_13.1.0_MAC.dmg
OfflineApps: Found major version:  
OfflineApps: Latest version found:  
OfflineApps: Source path:  
OfflineApps: Downloading file:  
OfflineApps: Destination:  /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads//
Failed to download:  
Failed.
Receipt written to /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/receipts/Mathematica.download-receipt-20220718-140835.plist

The following recipes failed:
    Mathematica.download.local
        Error in local.local.download.Mathematica: Processor: com.github.mlbz521.SharedProcessors/OfflineApps: Error: Failed to download:  

Nothing downloaded, packaged or imported.`

The recipe is definitely finding the .dmg in the path I specified, and it's also creating a "local.local.download.Mathematica" folder in the cache directory.

**Comment by MLBZ521** [comment]
@DrWebster Yeah, it's finding a matching file name, so that part is working.

One issue is its not identifying version/major version.
```
OfflineApps: Matched: Mathematica_13.1.0_MAC.dmg
OfflineApps: Found major version:
OfflineApps: Latest version found:
```

This is because, in your override, the `version_separator` value is `-` (which is the default, so it was not overridden/changed) and there is no `-` in that file name.  Someone else had a similar issue recently; see #39 built point 2 in my second to last comment.  In short, you'll need to either rename the file *or* drop the vendor's installer (aka that .dmg) in a folder that is labeled in a way that the processor can identify the required information.  (I do the latter at my institution so that whoever downloads the installer doesn't have to rename anything, just create a new folder with the version string and go.  Sometimes one of my colleagues that is primarily a Windows admin downloads the installers and this is an easy practice for anyone to follow.)

The next issue is the `Source path` is never set, so it can't "download" the file that was matched.
```
OfflineApps: Source path:
OfflineApps: Downloading file:
OfflineApps: Destination: /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads//
Failed to download:
```

This is likely because a `Latest version` was never identified because it couldn't parse a version string.  I think this second issue will be "resolved" (i.e. won't be a problem) once a version is identified in the step prior.  And further, I should probably update the processor to ensure that a `Latest version` was identified before attempting to download (so that it errors at the actual origin of the issue not further along).

**Comment by DrWebster** [comment]
@MLBZ521 thanks -- getting much closer now! I updated the override to change the separator to an underscore, then deleted the "_MAC" part from the filename (since the processor was getting tripped up on that). Now it finds the file and parses the version correctly. However, it's having problems mounting the image due to what appears to be a path problem in the cache directory:

OfflineApps: Matched:  Mathematica_13.1.0.dmg
OfflineApps: Found major version:  13
OfflineApps: Latest version found:  13.1.0
OfflineApps: Source path:  /Users/drwebster/Documents/autopkg/Mathematica_13.1.0.dmg
OfflineApps: Downloading file:  Mathematica_13.1.0.dmg
OfflineApps: Destination:  /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads/Mathematica_13.1.0.dmg/Mathematica_13.1.0.dmg
{'Output': {'cached_path': '/Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads/Mathematica_13.1.0.dmg',
            'download_changed': True,
            'found_major_version': '13',
            'version': '13.1.0'}}
FileFinder
{'Input': {'pattern': '/Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads/Mathematica_13.1.0.dmg/*.dmg'}}
FileFinder: No value supplied for find_method, setting default value of: glob
FileFinder: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognized
 with image /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads/Mathematica_13.1.0.dmg.
/Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads/Mathematica_13.1.0.dmg is not mounted
Failed.

The input pattern in the FileFinder section is correct -- the recipe builds a folder named "Mathematica_13.1.0.dmg" and copies the .dmg file into it -- but it looks like the rest of the process is trying to treat the folder itself as if it's the target .dmg?

**Comment by MLBZ521** [comment]
@DrWebster Yep, that (`_MAC`) would also be an issue.

I believe I have identified the issue.  It's basically due to me not testing the storing of the file in the `search_path` and not using a sub-folder (which is how I'm doing it).  I added this functionality earlier this year at someone else's request and I haven't test it.  I've made a few tweaks since adding, but no one has mentioned _this_ issue.

I have a fix for it, but I need to run a few recipes tomorrow first so I don't have to update the parent trust info.  I'll follow up with you once it's been updated.

**Comment by MLBZ521** [comment]
Oh and I also identified why this is happening and will include it in the fix as well:

>The next issue is the Source path is never set, so it can't "download" the file that was matched.
>```
>OfflineApps: Source path:
>OfflineApps: Downloading file:
>OfflineApps: Destination: /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/downloads//
>Failed to download:
>```
>This is likely because a Latest version was never identified because it couldn't parse a version string. I think this second issue will be "resolved" (i.e. won't be a problem) once a version is identified in the step prior. And further, I should probably update the processor to ensure that a Latest version was identified before attempting to download (so that it errors at the actual origin of the issue not further along).

**Comment by MLBZ521** [comment]
@DrWebster  Sorry for the delay again.  I've pushed the following commits that should resolve the issues identified above.
  * 42a5a4f
  * 791f3aa

Let me know your results after updating the local parent repo.

**Comment by DrWebster** [comment]
I updated the repo and gave it another shot, but now I'm getting a new error:

drw-mac:~ drwebster$ autopkg run Mathematica.download.local -vv
Processing Mathematica.download.local...
com.github.mlbz521.SharedProcessors/OfflineApps
{'Input': {'exception_string': 'Patch',
           'limitation_string': '',
           'major_version': '',
           'max_depth': '1',
           'search_path': '/Users/drwebster/Documents/autopkg/',
           'search_string': 'Mathematica',
           'version_separator': '_'}}
OfflineApps: No value supplied for OFFLINEAPPS_SMB_PORT, setting default value of: 445
OfflineApps: No value supplied for OFFLINEAPPS_SMB_MOUNT_POINT, setting default value of: /private/tmp/OfflineApps
OfflineApps: No value supplied for check_filesize, setting default value of: True
local variable 'name' referenced before assignment
Failed.
Receipt written to /Users/drwebster/Library/AutoPkg/Cache/local.local.download.Mathematica/receipts/Mathematica.download-receipt-20220726-085549.plist

The following recipes failed:
    Mathematica.download.local
        Error in local.local.download.Mathematica: Processor: com.github.mlbz521.SharedProcessors/OfflineApps: Error: local variable 'name' referenced before assignment

Nothing downloaded, packaged or imported.

**Comment by MLBZ521** [comment]
@DrWebster  Whoops, fixed in afd1649.

**Comment by DrWebster** [comment]
@MLBZ521 Works great now! Thanks for your help!

**Comment by MLBZ521** [comment]
@DrWebster Great!  Glad it's working for you now and thanks for reporting it and helping me get it fixed.
