### ISSUE TITLE
Syntax error in JMP.pkg recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/MLBZ521-recipes#55]
Seeing the following this morning:

 WARNING: plist error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/JMP/JMP.pkg.recipe: not well-formed (invalid token): line 24, column 11

**Comment by MLBZ521** [comment]
Whoops, my bad.  Thanks for the PR.
