### ISSUE TITLE
Zoom Version String Changed

### ISSUE THREAD

**Issue by jchutc0** [autopkg/MLBZ521-recipes#6]
It appears that the newer versions of zoom.us have a changed version name that breaks the packager (Zoom-ForIT.pkg). The new short bundle versions contain parentheses, and there is a failure when trying to rename the package with those. I was able to fix the problem by changing the plist_version_key in the recipe to use CLBundleVersion instead of the short version, but wanted to share in case anyone else was seeing the same problem.

**Comment by MLBZ521** [comment]
Please see my response to #3 .
