### ISSUE TITLE
Screencast-O-Matic is now Screen Pal

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/MLBZ521-recipes#60]
Hi, @MLBZ521 

The Screencast-O-Matic download recipe is currently failing with the follow error
```
Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
```

Seems the vendor is having a bit of rebrand of their offerings. https://screenpal.com/blog/screenpal-announcement/

Not sure how you want to deal with this? Deprecate these recipes and create new ones? If you no longer need this software we could host the new recipes? Let me know what you think, I'm happy to help create new ones if needed too.

Thanks!

**Comment by MLBZ521** [comment]
Hey Paul,

Yeah, I saw this recently.  I do need to do something for it.  I'm a couple weeks behind on my recipes failing in my AutoPkg instance due to some other stuff I'm working on.  I'll see if I can get to it by next week.

Thanks for the heads-up!

**Comment by macmule** [comment]
@MLBZ521, we'll create ScreenPal recipes and you can then deprecate you Screencast-O-Matic citing the ScreenPal recipes

**Comment by paul-cossey** [comment]
Hi, @MLBZ521 

ScreenPal 3 Recipes are now live on our repo https://github.com/autopkg/dataJAR-recipes/commit/1f646a76b1a14caffa9700de12de15aaf4544d14

**Comment by MLBZ521** [comment]
Thanks guys.  I'm finally getting to play catch up here.

Looks like the app is still the weird, Java-based application with a new front end.  I bet it still doesn't play well in multiple user environments....  I'll do some testing on that soon.

I went ahead and created a .pkg recipe in my repo for Screen Pal as well:  [ScreenPal3.pkg.recipe.yaml](https://github.com/autopkg/MLBZ521-recipes/blob/master/ScreenPal/ScreenPal3.pkg.recipe.yaml)
