### ISSUE TITLE
SolsticeProcessor error

### ISSUE THREAD

**Issue by eshirk** [autopkg/MLBZ521-recipes#61]
Wondering if anybody else is getting the following from the Solstice.pkg recipe:

        Error in local.pkg.Solstice: Processor: SolsticeProcessor: Error: The Mersive Solstice.app wasn't at the expected location.

The expected location is the logged-in user's desktop, and Mersive Solstice.app is definitely there.

**Comment by MLBZ521** [comment]
Hey @eshirk, sorry for the delay on this.  Were you able to track down the issue by chance?

My AutoPkg runner hasn't been showing any issues like this...  I wonder if it's a timing thing or something like that, possibly?

**Comment by eshirk** [comment]
No worries, @MLBZ521 ; I ended up moving the recipe to our monthly build job, so haven't really been paying attention.  I checked just now and I'm not getting that error any longer.

However, it looks like the current app version is v6.1, but the download recipe is still pulling v5.5.

**Comment by MLBZ521** [comment]
Ah, well.....looks like several others have create recipes for Solstice....and appears that the download changed quite some time ago...  Whoops, I didn't realize.

That said, I'm going to deprecate my download recipe and will update my pkg recipe to point to a new [download recipe](github.com/autopkg/joshua-d-miller-recipes/blob/master/Mersive/SolsticeClient.download.recipe).  However, that download recipe is currently broken, which I just submitted a [PR](https://github.com/autopkg/joshua-d-miller-recipes/pull/152) with a fix.

Once/if that PR is merged, I'll commit my new pkg recipe and will close this issue.

**Comment by MLBZ521** [comment]
Ok, I forgot about this as I had several PR's open and waiting on them for various things...  The PR was merged, so I have now deprecated my old recipes and just pushed a new .pkg recipe.

The new recipe identifier is `com.github.mlbz521.pkg.SolsticeClient` to not conflict with the old recipe identifier.

I'll go ahead and close this issue, but if you still have a problem, feel free to reopen.
