### ISSUE TITLE
QGIS download URL not found

### ISSUE THREAD

**Issue by rustymyers** [autopkg/MLBZ521-recipes#73]
The current recipe looks for the full regex match of an URL: https://github.com/autopkg/MLBZ521-recipes/blob/209722e3d3918b8ecfd80a097d6f5d0ab0048780/QGIS/QGIS.download.recipe#L22

The latest changes to the QGIS download page remove the full URL and replace it with a relative link.
`<a class="button is-primary1 is-outlined mb-3" href=/downloads/macos/qgis-macos-pr.dmg onclick=thanks(this) download>Latest Version for Mac OS (3.38)</a></p><p>Alternatively, for native support of both Intel x86 and Apple ARM architectures, together with the latest versions of key components (e.g. GDAL, PDAL, GRASS GIS) see <a href=https://www.qgis.org/resources/installation-guide/#macports>MacPorts Installing Instructions</a></p><p><div class="container rich tips"><div class=icon>💁</div><div class="cont coloring-1"></p><h5 id=tips-for-first-launch>Tips for first launch`

**Comment by rustymyers** [comment]
Pull request #72 fixes this issue. @MLBZ521

**Comment by MLBZ521** [comment]
Sorry for the delay.  I just merged #72.
