### ISSUE TITLE
Amazon Corretto Issues

### ISSUE THREAD

**Issue by M1kep** [autopkg/MLBZ521-recipes#9]
So, this may be user error... When attempting to the use the Amazon Corretto recipe I'm receiving the below error:

`JSSImporter can't find a package at '%RECIPE_CACHE_DIR%/%NAME%-%version%.pkg'!`

The `jvm_version` is being set as well as the pkg being created. From my initial looks, it appears that the jss recipe `pkg_path` is using `%version%` instead of `jvm_version` (https://github.com/autopkg/MLBZ521-recipes/blob/master/AmazonCorretto/AmazonCorretto.jss.recipe#L55) I'd submit a PR, but I'm not even positive if this is the actual cause

**Comment by M1kep** [comment]
Okay, so two things I've tested:

1. Updating the recipe to use `%jvm_version%`: This works, but leads to the package not having the "Version" flag set:
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/2661819/74792741-298c5200-5273-11ea-8819-01c5d837d5c1.png">

2. Updating the processor script to also set the version environment variable:
```
        if jvm_version:
            self.env["jvm_version"] = jvm_version
            self.env["version"] = jvm_version
            self.output("jvm_version: {}".format(self.env["jvm_version"]))
        else:
            raise ProcessorError("Unable to determine the Java Virtual Machine version.")
```

**Comment by MLBZ521** [comment]
Not sure if I paid attention to this after I recently updated this recipe and the associated processor...  I'm actually in the middle of completely revamping my autopkg workflow at work and so I haven't actually ran the updated recipe through a "real" run.  I really only tested to make sure it downloaded and packaged, didn't look at the meta data to honest.  I also need to push the Python3 updates to the master branch as well...

Give me a few more days and I'll hopefully get caught up and can give this a look, if you do not figure it out in the mean time.

**Comment by M1kep** [comment]
Sounds good! For now, I think the fix is to add the `self.env["version"] = jvm_version` line. If it makes it easier, it can hold off until you've pushed some of the larger changes up!

**Comment by MLBZ521** [comment]
I made the following changing a little bit earlier:
7ff69a4
f832263

Those resolved it in my test runs.  Basically, they're reverting recent changes...not sure what I was thinking, but it was the first time I looked at recipes in a few months...and I didn't test the JSS recipes...so...yeah.

Thanks for the heads up.  Let me know if that doesn't fix it for you.  👍

**Comment by M1kep** [comment]
So the package issue is fixed! Only thing is that the commit seemed to break the Python 2 backwards compatibility. As I currently have both autopkg version running due to a migration I'll do some testing and throw over a small PR to add backwards compatibility to it
